# Generated by Django 5.2.16 on 2026-07-17 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drivetrain', models.CharField(blank=True, max_length=8)),
                ('year_from', models.PositiveSmallIntegerField()),
                ('year_to', models.PositiveSmallIntegerField(default=9999)),
                ('position', models.CharField(blank=True, max_length=24)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_exclusion', models.BooleanField(default=False)),
                ('source', models.CharField(default='manual', max_length=32)),
                ('confidence', models.FloatField(default=1.0)),
                ('engine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicleengine')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehiclegeneration')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitments', to='catalog.product')),
                ('trim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicletrim')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['generation', 'year_from', 'year_to'], name='fitment_fit_generat_effcc4_idx'), models.Index(fields=['product'], name='fitment_fit_product_d68460_idx')],
            },
        ),
        migrations.CreateModel(
            name='FitmentIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=24)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehiclevariant')),
            ],
            options={
                'verbose_name_plural': 'fitment index entries',
                'indexes': [models.Index(fields=['variant', 'category'], name='fitment_fit_variant_fcf5b8_idx'), models.Index(fields=['variant', 'brand'], name='fitment_fit_variant_92beb1_idx')],
                'unique_together': {('product', 'variant', 'position')},
            },
        ),
    ]
