# Generated by Django 5.2.16 on 2026-07-17 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('slug', models.SlugField()),
                ('year_from', models.PositiveSmallIntegerField()),
                ('year_to', models.PositiveSmallIntegerField(default=9999)),
                ('body_type', models.CharField(blank=True, max_length=40)),
                ('facelift', models.CharField(blank=True, max_length=40)),
                ('image', models.ImageField(blank=True, upload_to='generations/')),
            ],
            options={
                'ordering': ['-year_from'],
            },
        ),
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='makes/')),
                ('popularity', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-popularity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(max_length=80)),
                ('code', models.CharField(blank=True, max_length=40)),
                ('slug', models.SlugField()),
                ('fuel', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric'), ('lpg', 'LPG')], max_length=16)),
                ('capacity_cc', models.PositiveIntegerField(blank=True, null=True)),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engines', to='vehicles.vehiclegeneration')),
            ],
            options={
                'unique_together': {('generation', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField()),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='vehicles.vehiclemake')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('make', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='vehiclegeneration',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generations', to='vehicles.vehiclemodel'),
        ),
        migrations.CreateModel(
            name='VehicleModelAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(db_index=True, max_length=120)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='vehicles.vehiclemodel')),
            ],
            options={
                'verbose_name_plural': 'vehicle model aliases',
            },
        ),
        migrations.CreateModel(
            name='VehicleTrim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField()),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trims', to='vehicles.vehiclegeneration')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('generation', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='VehicleVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drivetrain', models.CharField(blank=True, max_length=8)),
                ('transmission', models.CharField(blank=True, max_length=16)),
                ('year_from', models.PositiveSmallIntegerField()),
                ('year_to', models.PositiveSmallIntegerField(default=9999)),
                ('market', models.CharField(default='KE', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('engine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicleengine')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='vehicles.vehiclegeneration')),
                ('trim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicletrim')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleRegistrationLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(db_index=True, max_length=16)),
                ('vin', models.CharField(blank=True, db_index=True, max_length=32)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(default=0)),
                ('resolved_at', models.DateTimeField(auto_now=True)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehiclevariant')),
            ],
        ),
        migrations.CreateModel(
            name='VariantGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_from', models.PositiveSmallIntegerField()),
                ('year_to', models.PositiveSmallIntegerField(default=9999)),
                ('slug_years', models.CharField(max_length=16)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('canonical_path', models.CharField(max_length=400, unique=True)),
                ('product_count', models.PositiveIntegerField(default=0)),
                ('engine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicleengine')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='vehicles.vehiclegeneration')),
                ('trim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicletrim')),
                ('variants', models.ManyToManyField(related_name='groups', to='vehicles.vehiclevariant')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='vehiclegeneration',
            unique_together={('model', 'slug')},
        ),
        migrations.AddIndex(
            model_name='vehiclevariant',
            index=models.Index(fields=['generation', 'year_from', 'year_to'], name='vehicles_ve_generat_a11c6c_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehiclevariant',
            constraint=models.CheckConstraint(condition=models.Q(('year_to__gte', models.F('year_from'))), name='variant_year_order'),
        ),
    ]
