# Generated by Django 5.2.16 on 2026-07-17 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('vehicle', 'Vehicle storefront'), ('vehicle_category', 'Vehicle + category'), ('category', 'Category'), ('brand', 'Brand'), ('product', 'Product')], db_index=True, max_length=24)),
                ('path', models.CharField(max_length=400, unique=True)),
                ('product_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('directive', models.CharField(choices=[('index', 'index'), ('noindex', 'noindex'), ('canonical', 'canonical'), ('410', '410 Gone')], db_index=True, default='noindex', max_length=12)),
                ('canonical_to', models.CharField(blank=True, max_length=400)),
                ('priority', models.FloatField(default=0.5)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('h1', models.CharField(blank=True, max_length=200)),
                ('intro_html', models.TextField(blank=True)),
                ('manual_override', models.BooleanField(default=False)),
                ('impressions_30d', models.PositiveIntegerField(default=0)),
                ('clicks_30d', models.PositiveIntegerField(default=0)),
                ('last_computed', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('variant_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.variantgroup')),
            ],
        ),
    ]
